version: "3.7"
services:
  style:
    image: catchdigital/node-sass
    command: sh -c "
      node-sass -r -o /code/static/css/ /code/stylesheets/
      && node-sass -r -w -o /code/static/css/ /code/stylesheets/"
    volumes:
      - .:/code
  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PWD}
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    build: .
    env_file:
      - .env
    command: bash -c "/code/scripts/run_prod.sh"
    volumes:
      - .:/code
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - db
      - style

  # caddy:
  #   image: caddy:2.2.1
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile
  #     - ./staticfiles:/var/www/static
  #     - ./media:/var/www/media
  #     - caddy_data:/data
  #     - caddy_config:/config
  #   depends_on:
  #     - web

volumes:
  # web-static:
  # web-media:
  # caddy_data:
  # caddy_config:
  db-data:
