# Generated by Django 3.2 on 2021-05-26 06:29

import apps.contact.models
from django.db import migrations, models
import django_enumfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studio', '0003_auto_20210503_0535'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16)),
                ('contactnumber_type', django_enumfield.db.fields.EnumField(enum=apps.contact.models.ContactNumber.ContactNumberType)),
            ],
            options={
                'verbose_name': 'Contact Number type',
                'verbose_name_plural': 'B - Contact Number types ',
            },
        ),
        migrations.CreateModel(
            name='EmailQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('email_type', django_enumfield.db.fields.EnumField(enum=apps.contact.models.EmailQuery.EmailQueryType)),
                ('text', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Email type',
                'verbose_name_plural': 'A - Email type',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('contact_number', models.ManyToManyField(to='contact.ContactNumber')),
                ('query_type', models.ManyToManyField(to='contact.EmailQuery')),
                ('social_media', models.ManyToManyField(to='studio.SocialMedia')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'C - Contacts ',
            },
        ),
    ]
