# Generated by Django 3.2 on 2021-04-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
                ("icon", models.ImageField(upload_to="social_media_icons")),
            ],
            options={
                "verbose_name": "Social media",
                "verbose_name_plural": "A - Social medias",
            },
        )
    ]
