# Generated by Django 3.2 on 2021-04-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("studio", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="People",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("job_title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("social_medias", models.ManyToManyField(to="studio.SocialMedia")),
            ],
            options={"verbose_name": "People", "verbose_name_plural": "A - People"},
        )
    ]
