# Generated by Django 3.2 on 2021-05-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_auto_20210503_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='people'),
        ),
    ]
