# Generated by Django 3.2 on 2021-06-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_socialmedia_related_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='social_medias',
            field=models.ManyToManyField(blank=True, to='studio.SocialMedia'),
        ),
    ]
