# Generated by Django 3.2 on 2021-05-03 06:45

import apps.main.models
from django.db import migrations, models
import django_enumfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('page_type', django_enumfield.db.fields.EnumField(blank=True, enum=apps.main.models.Page.PageType, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Page setting',
                'verbose_name_plural': 'A - Page settings',
            },
        ),
    ]
