# Generated by Django 3.2 on 2021-04-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("work", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="WorkType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={"verbose_name": "Tag", "verbose_name_plural": "B - Work types"},
        )
    ]
