# Generated by Django 3.2 on 2021-04-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("work", "0002_worktype")]

    operations = [
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(max_length=255, upload_to="pictures")),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={"verbose_name": "Picture", "verbose_name_plural": "C - Pictures"},
        )
    ]
