# Generated by Django 3.2 on 2021-04-30 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("work", "0003_picture")]

    operations = [
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artwork",
                    models.FileField(blank=True, null=True, upload_to="artworks"),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, max_length=255, null=True, upload_to="cover_images"
                    ),
                ),
                ("list_description", models.TextField()),
                ("is_featured_in_dashboard", models.BooleanField(default=False)),
                ("picture", models.ManyToManyField(to="work.Picture")),
                ("tags", models.ManyToManyField(to="work.Tag")),
                (
                    "work_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="work.worktype"
                    ),
                ),
            ],
            options={"verbose_name": "Work", "verbose_name_plural": "D - Works"},
        )
    ]
