# Generated by Django 3.2 on 2021-05-03 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_work'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worktype',
            options={'verbose_name': 'Type', 'verbose_name_plural': 'B - Work types'},
        ),
    ]
