# Generated by Django 3.2 on 2021-06-04 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_auto_20210517_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
