# Generated by Django 3.2 on 2021-06-23 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_auto_20210517_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=256)),
                ('feature_description', models.CharField(max_length=256)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work.work')),
            ],
            options={
                'verbose_name': 'Work Feature',
                'verbose_name_plural': 'E - Work Features',
            },
        ),
    ]
