# Generated by Django 3.2 on 2021-07-14 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_work_title'),
        ('work', '0008_alter_workfeature_work'),
    ]

    operations = [
    ]
