# Generated by Django 3.2 on 2021-07-01 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_workfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workfeature',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.work'),
        ),
    ]
